import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { join, posix } from "node:path";
import { atomicWriteFile } from "../merge/safeWrite.js";

/**
 * Integrity manifest for hatch3r canonical files.
 *
 * **Guarantees:**
 * - Detects unauthorized modifications to hatch3r-managed files (agents, rules, skills, commands, hooks, prompts).
 * - Detects missing or newly added files relative to the last `hatch3r init` or `hatch3r update`.
 * - Manifest-level checksum detects tampering with the integrity file itself.
 *
 * **Limitations:**
 * - Content-addressed only: detects WHAT changed, not WHO or WHEN.
 * - No signing: an attacker with write access can regenerate a valid manifest.
 * - Symlinks are excluded from scanning to prevent symlink-based bypass.
 * - Only scans `.md`, `.mdc`, and `.json` files in designated directories.
 */
export interface IntegrityManifest {
  version: number;
  generated: string;
  hatchVersion: string;
  /** Tool and version that generated this manifest. Present in manifests generated by hatch3r >=1.5.0. */
  generatedBy?: { tool: string; version: string };
  /**
   * D1-SA1.3.2 (High): Adapters the caller intended to run at seal time
   * (the full tool list from hatch.json). Consumers can compare this against
   * `successfulAdapters` to detect partial-failure syncs without needing to
   * re-read hatch.json. Optional for backward compatibility with manifests
   * sealed by hatch3r <1.6.0.
   */
  expectedAdapters?: string[];
  /**
   * D1-SA1.3.2 (High): Adapters that produced outputs successfully during the
   * sync that sealed this manifest. When this set is a proper subset of
   * `expectedAdapters`, the adapter output directories for the missing tools
   * may be stale or absent. Optional for backward compatibility.
   */
  successfulAdapters?: string[];
  files: Record<string, string>;
  checksum: string;
}

/**
 * Options for {@link generateIntegrityManifest} controlling metadata fields
 * that record which adapters the sealing sync attempted and which succeeded.
 */
export interface GenerateIntegrityManifestOptions {
  /** Adapters that were configured to run (from hatch.json tools). */
  expectedAdapters?: string[];
  /** Adapters that produced output successfully during this sync. */
  successfulAdapters?: string[];
}

export interface VerifyResult {
  file: string;
  status: "pass" | "modified" | "missing" | "new" | "tampered";
  expected?: string;
  actual?: string;
}

const INTEGRITY_FILE = ".integrity.json";
const SCANNED_DIRS = ["agents", "commands", "rules", "skills", "hooks", "prompts", "github-agents", "mcp"];

/** Compute a SHA-256 hash of a UTF-8 string, prefixed with `sha256:`. */
function sha256(content: string): string {
  return `sha256:${createHash("sha256").update(content, "utf-8").digest("hex")}`;
}

/** Recursively collect `.md`, `.mdc`, and `.json` file paths from a directory, skipping symlinks. */
async function collectFiles(dir: string, base: string): Promise<string[]> {
  const files: string[] = [];
  let entries: { name: string; isDirectory: () => boolean; isFile: () => boolean; isSymbolicLink: () => boolean }[];
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return files;
    throw err;
  }
  for (const entry of entries) {
    if (entry.isSymbolicLink()) continue;
    const fullPath = join(dir, entry.name);
    const relPath = posix.join(base, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectFiles(fullPath, relPath)));
    } else if (entry.isFile() && (entry.name.endsWith(".md") || entry.name.endsWith(".mdc") || entry.name.endsWith(".json"))) {
      files.push(relPath);
    }
  }
  return files;
}

/**
 * Generate an integrity manifest by hashing all canonical files in the .agents directory.
 *
 * Scans `.md`, `.mdc`, and `.json` files in designated subdirectories
 * and produces a SHA-256 hash for each. The manifest-level checksum
 * covers the entire file hash map to detect tampering.
 *
 * Optionally records which adapters the caller expected to run
 * (`expectedAdapters`) and which succeeded (`successfulAdapters`) so that
 * downstream tools (`hatch3r status`, `hatch3r verify`) can detect
 * partial-failure syncs without re-reading `hatch.json`.
 */
export async function generateIntegrityManifest(
  agentsDir: string,
  hatchVersion: string,
  options: GenerateIntegrityManifestOptions = {},
): Promise<IntegrityManifest> {
  const files: Record<string, string> = {};

  for (const dir of SCANNED_DIRS) {
    const dirPath = join(agentsDir, dir);
    const mdFiles = await collectFiles(dirPath, dir);
    for (const relPath of mdFiles) {
      const content = await readFile(join(agentsDir, relPath), "utf-8");
      files[relPath] = sha256(content);
    }
  }

  const checksum = createHash("sha256")
    .update(JSON.stringify(files))
    .digest("hex");

  const manifest: IntegrityManifest = {
    version: 1,
    generated: new Date().toISOString(),
    hatchVersion,
    generatedBy: { tool: "hatch3r", version: hatchVersion },
    files,
    checksum,
  };

  if (options.expectedAdapters) {
    // Deterministic sort so semantically-equivalent syncs produce identical
    // manifests (aids diffing and test assertions).
    manifest.expectedAdapters = [...options.expectedAdapters].sort();
  }
  if (options.successfulAdapters) {
    manifest.successfulAdapters = [...options.successfulAdapters].sort();
  }

  return manifest;
}

/** Atomically write the integrity manifest to `.agents/.integrity.json`. */
export async function writeIntegrityManifest(
  agentsDir: string,
  manifest: IntegrityManifest,
): Promise<void> {
  const filePath = join(agentsDir, INTEGRITY_FILE);
  await atomicWriteFile(filePath, JSON.stringify(manifest, null, 2) + "\n");
}

/** Runtime type guard that validates an unknown value conforms to the IntegrityManifest shape. */
function validateIntegrityManifest(data: unknown): data is IntegrityManifest {
  if (typeof data !== "object" || data === null) return false;
  const obj = data as Record<string, unknown>;
  if (typeof obj.version !== "number") return false;
  if (typeof obj.generated !== "string") return false;
  if (typeof obj.hatchVersion !== "string") return false;
  // generatedBy is required in new manifests but tolerated absent for backward compat
  if (obj.generatedBy !== undefined) {
    if (typeof obj.generatedBy !== "object" || obj.generatedBy === null) return false;
    const gb = obj.generatedBy as Record<string, unknown>;
    if (typeof gb.tool !== "string" || typeof gb.version !== "string") return false;
  }
  // D1-SA1.3.2: expectedAdapters/successfulAdapters are optional string arrays.
  // Validate when present so malformed values do not silently coerce to `any`.
  if (obj.expectedAdapters !== undefined) {
    if (!Array.isArray(obj.expectedAdapters)) return false;
    for (const v of obj.expectedAdapters) {
      if (typeof v !== "string") return false;
    }
  }
  if (obj.successfulAdapters !== undefined) {
    if (!Array.isArray(obj.successfulAdapters)) return false;
    for (const v of obj.successfulAdapters) {
      if (typeof v !== "string") return false;
    }
  }
  if (typeof obj.files !== "object" || obj.files === null) return false;
  for (const val of Object.values(obj.files as Record<string, unknown>)) {
    if (typeof val !== "string") return false;
  }
  if (typeof obj.checksum !== "string") return false;
  return true;
}

/** Read and validate the integrity manifest, returning null if absent or malformed. */
export async function readIntegrityManifest(
  agentsDir: string,
): Promise<IntegrityManifest | null> {
  try {
    const raw = await readFile(join(agentsDir, INTEGRITY_FILE), "utf-8");
    const parsed: unknown = JSON.parse(raw);
    if (!validateIntegrityManifest(parsed)) return null;
    return parsed;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
    if (err instanceof SyntaxError) return null;
    throw err;
  }
}

/**
 * Verify integrity of all canonical files against the stored manifest.
 *
 * Returns an array of per-file results: `pass`, `modified`, `missing`,
 * `new` (file on disk but not in manifest), or `tampered` (manifest
 * checksum mismatch). Returns an empty array if no manifest exists.
 */
export async function verifyIntegrity(
  agentsDir: string,
): Promise<VerifyResult[]> {
  const manifest = await readIntegrityManifest(agentsDir);
  if (!manifest) {
    return [];
  }

  const results: VerifyResult[] = [];

  const expected = createHash("sha256")
    .update(JSON.stringify(manifest.files))
    .digest("hex");
  if (manifest.checksum !== expected) {
    results.push({ file: INTEGRITY_FILE, status: "tampered" });
    return results;
  }
  const manifestFiles = new Set(Object.keys(manifest.files));

  for (const [filePath, expectedHash] of Object.entries(manifest.files)) {
    const fullPath = join(agentsDir, filePath);
    try {
      const content = await readFile(fullPath, "utf-8");
      const actualHash = sha256(content);
      if (actualHash === expectedHash) {
        results.push({ file: filePath, status: "pass" });
      } else {
        results.push({
          file: filePath,
          status: "modified",
          expected: expectedHash,
          actual: actualHash,
        });
      }
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") {
        results.push({
          file: filePath,
          status: "missing",
          expected: expectedHash,
        });
      } else {
        throw err;
      }
    }
  }

  for (const dir of SCANNED_DIRS) {
    const dirPath = join(agentsDir, dir);
    const onDisk = await collectFiles(dirPath, dir);
    for (const filePath of onDisk) {
      if (!manifestFiles.has(filePath)) {
        const content = await readFile(join(agentsDir, filePath), "utf-8");
        results.push({
          file: filePath,
          status: "new",
          actual: sha256(content),
        });
      }
    }
  }

  results.sort((a, b) => a.file.localeCompare(b.file));
  return results;
}
