import type { AdapterOutput } from "../types.js";
import { wrapInManagedBlock } from "../merge/managedBlocks.js";
import { BaseAdapter, output, type AdapterContext } from "./base.js";
import { readCanonicalFiles } from "./canonical.js";
import { applyCustomization } from "./customization.js";
import { resolveAgentModel } from "../models/resolve.js";

// AGENTS.md adapter — generates a standalone AGENTS.md file at the project root
// following the AAIF (AI Agent Instruction File) convention. Over 60K repos use
// this format to declare agent capabilities, instructions, and rules in a single
// discoverable markdown file.
export class AgentsMdAdapter extends BaseAdapter {
  readonly name = "agents-md";

  protected async doGenerate(ctx: AdapterContext): Promise<AdapterOutput[]> {
    const minimal = this.isMinimal(ctx);
    const sections: string[] = [];

    // Header
    sections.push("# Agents");
    sections.push("");
    if (!minimal) {
      sections.push("This file defines the available AI agents, rules, and skills for this project.");
      sections.push("Generated by [hatch3r](https://github.com/hatch3r/hatch3r).");
      sections.push("");
    }

    // Bridge orchestration
    const orchestration = await this.bridgeOrchestration(ctx);
    if (orchestration.trim()) {
      sections.push(orchestration);
      sections.push("");
    }

    // Agents section
    if (ctx.features.agents) {
      const agents = await readCanonicalFiles(ctx.agentsDir, "agents", this.warnings);
      for (const agent of agents) {
        const { content, skip, overrides, warnings } = await applyCustomization(ctx.projectRoot, agent);
        this.warnings.push(...warnings);
        if (skip) continue;
        const desc = overrides.description ?? agent.description;
        const model = resolveAgentModel(agent.id, agent, ctx.manifest, overrides);

        sections.push(`## Agent: ${agent.id}`);
        sections.push("");
        if (!minimal) {
          sections.push(desc);
          sections.push("");
        }
        if (model) {
          sections.push(`**Model:** \`${model}\``);
          sections.push("");
        }
        sections.push("### Instructions");
        sections.push("");
        sections.push(minimal ? this.stripMinimal(content) : content);
        sections.push("");
      }
    }

    // Rules section
    if (ctx.features.rules) {
      const rules = await readCanonicalFiles(ctx.agentsDir, "rules", this.warnings);
      const enabledRules: Array<{ id: string; description: string; content: string }> = [];
      for (const rule of rules) {
        const { content, skip, overrides, warnings } = await applyCustomization(ctx.projectRoot, rule);
        this.warnings.push(...warnings);
        if (skip) continue;
        const desc = overrides.description ?? rule.description;
        enabledRules.push({ id: rule.id, description: desc, content });
      }
      if (enabledRules.length > 0) {
        sections.push("## Rules");
        sections.push("");
        for (const rule of enabledRules) {
          sections.push(`### ${rule.id}`);
          sections.push("");
          if (!minimal) {
            sections.push(rule.description);
            sections.push("");
          }
          sections.push(minimal ? this.stripMinimal(rule.content) : rule.content);
          sections.push("");
        }
      }
    }

    // Skills section
    if (ctx.features.skills) {
      const skills = await readCanonicalFiles(ctx.agentsDir, "skills", this.warnings);
      const enabledSkills: Array<{ id: string; description: string; content: string }> = [];
      for (const skill of skills) {
        const { content, skip, overrides, warnings } = await applyCustomization(ctx.projectRoot, skill);
        this.warnings.push(...warnings);
        if (skip) continue;
        const desc = overrides.description ?? skill.description;
        enabledSkills.push({ id: skill.id, description: desc, content });
      }
      if (enabledSkills.length > 0) {
        sections.push("## Skills");
        sections.push("");
        for (const skill of enabledSkills) {
          sections.push(`### ${skill.id}`);
          sections.push("");
          if (!minimal) {
            sections.push(skill.description);
            sections.push("");
          }
          sections.push(minimal ? this.stripMinimal(skill.content) : skill.content);
          sections.push("");
        }
      }
    }

    const inner = sections.join("\n");
    return [output("AGENTS.md", wrapInManagedBlock(inner), inner)];
  }
}
