import { join } from "node:path";
import chalk from "chalk";
import { printBanner, error as logError, warn } from "../shared/ui.js";
import { AGENTS_DIR, HatchError } from "../../types.js";
import { verifyIntegrity } from "../../integrity/index.js";

/**
 * Refuse to proceed when canonical files have drifted unless `--force` is set.
 *
 * C7-H5 (D15, OWASP ASI 2026): All mutation commands (init/sync/update/add)
 * must run a preflight integrity check so silent tampering is not amplified
 * downstream. Centralised here so future `add` work uses the same guard.
 */
async function preflightIntegrityCheck(rootDir: string, force: boolean): Promise<void> {
  const agentsDir = join(rootDir, AGENTS_DIR);
  const results = await verifyIntegrity(agentsDir);
  if (results.length === 0) return; // No manifest yet — nothing to verify.

  const modified = results.filter((r) => r.status === "modified");
  const missing = results.filter((r) => r.status === "missing");
  const tampered = results.filter((r) => r.status === "tampered");
  const driftDetected = modified.length > 0 || missing.length > 0 || tampered.length > 0;
  if (!driftDetected) return;

  warn("Integrity issues detected before add:");
  for (const r of tampered) warn(`  TAMPERED: ${r.file}`);
  for (const r of modified) warn(`  MODIFIED: ${r.file}`);
  for (const r of missing) warn(`  MISSING:  ${r.file}`);

  if (!force) {
    logError(
      "Refusing to add with integrity drift. Run `hatch3r verify` to inspect, " +
      "or re-run with --force to proceed.",
    );
    throw new HatchError(
      "Integrity drift detected (use --force to override)",
      1,
      "INTEGRITY_ERROR",
    );
  }
  warn("Continuing with --force: drifted files will not be regenerated by `add`.");
  console.log();
}

export async function addCommand(opts: { force?: boolean } = {}): Promise<void> {
  printBanner(true);
  // C7-H5 (D15): Preflight integrity check runs before any future mutation
  // logic in this command, even though the body currently exits early with
  // a "not yet implemented" error. When the command is wired up, the guard
  // is already in place — no second pass required.
  await preflightIntegrityCheck(process.cwd(), !!opts.force);

  console.log();
  warn("The `add` command is not yet implemented.");
  console.log(chalk.dim("  It will allow installing community packs in a future release."));
  console.log(chalk.dim("  Follow https://github.com/hatch3r for updates."));
  console.log();
  throw new HatchError(
    "The `add` command is not yet implemented.",
    2,
    "VALIDATION_ERROR",
  );
}
