export type Platform = "github" | "azure-devops" | "gitlab";

export interface ModelConfig {
  default?: string;
  agents?: Record<string, string>;
}

export interface ClaudeConfig {
  permissions?: {
    allow?: string[];
    deny?: string[];
  };
  /**
   * Claude Code Agent Teams teammate display mode.
   *
   * GA values: "auto" (default), "in-process", "tmux".
   * Deprecated values (pre-GA): "tool-using", "full-trust", "manual-approval".
   * #264 (D9-9.35): Legacy values are still accepted for backward compatibility
   * but map to "auto" at runtime. Use GA values in new configurations.
   */
  teammateMode?: "auto" | "in-process" | "tmux" | "tool-using" | "full-trust" | "manual-approval";
  agentTeams?: boolean | "ga";
}

/** Controls how adapter output is generated (verbosity), not what content is selected. */
export type GenerationMode = "standard" | "minimal";

export interface CostTrackingConfig {
  /** Maximum estimated cost per session in configured currency. */
  sessionBudget?: number;
  /** Maximum estimated cost per issue in configured currency. */
  issueBudget?: number;
  /** Maximum estimated cost per epic in configured currency. */
  epicBudget?: number;
  /** Currency code for cost display (default: "USD"). */
  currency?: string;
  /** Budget percentage thresholds that trigger warnings (default: [0.5, 0.75, 0.9]). */
  warningThresholds?: number[];
  /** When true, halt work when budget is exhausted. When false, warn only (default: false). */
  hardStop?: boolean;
}

export interface HatchManifest {
  version: string;
  hatch3rVersion: string;
  platform?: Platform;
  owner: string;
  repo: string;
  namespace: string;
  project: string;
  tools: Tool[];
  features: Features;
  mcp: McpConfig;
  board?: BoardConfig;
  repos?: RepoEntry[];
  packages?: PackageEntry[];
  hooks?: HooksConfig;
  models?: ModelConfig;
  claude?: ClaudeConfig;
  /** Token usage and cost tracking configuration. */
  costTracking?: CostTrackingConfig;
  /** Content selection from init. undefined = legacy "full" (backward compat). */
  content?: ContentSelection;
  /** Detected project languages from repo analysis. */
  languages?: string[];
  /** Git worktree file-isolation settings. */
  worktree?: WorktreeConfig;
  /** Tracks project specs generated by /project-spec or /api-spec commands. */
  specs?: {
    paths: string[];
    lastGenerated?: string;
  };
  /** Present when this repo is managed by a workspace. */
  workspace?: {
    /** Relative path from this repo back to workspace root. */
    rootPath: string;
    /** ISO timestamp of last workspace sync. */
    lastSync: string;
    /** hatch3r version used for last sync. */
    syncVersion: string;
    /** SHA-256 of workspace.json at time of sync. */
    workspaceChecksum: string;
    /** Content IDs explicitly excluded by this repo. */
    excludedContent?: string[];
    /** Content IDs added locally (not from workspace). */
    localContent?: string[];
  };
  managedFiles: string[];
}

export interface WorktreeConfig {
  enabled: boolean;
  /** Additional user-specified gitignore patterns to include. */
  extraPatterns?: string[];
  /** Strategy for node_modules: "symlink" (default) or "skip". */
  nodeModules?: "symlink" | "skip";
}

export const TOOLS = ["cursor", "copilot", "claude", "opencode", "windsurf", "amp", "codex", "gemini", "cline", "aider", "kiro", "goose", "zed", "amazon-q", "antigravity", "agents-md"] as const;
export type Tool = (typeof TOOLS)[number];
export const VALID_TOOLS = new Set<string>(TOOLS);
export const TOOL_CHOICES = TOOLS.join(", ");

/** Tools that support git worktree file isolation. Shared across init, update, and config. */
export const WORKTREE_CAPABLE_TOOLS = new Set<string>(["claude"]);

export interface BoardConfig {
  owner: string;
  repo: string;
  /** Default branch for checkout, PR base, and release. Fallback: "main". */
  defaultBranch?: string;
  projectNumber: number | null;
  statusFieldId: number | null;
  statusOptions: {
    backlog: string | null;
    ready: string | null;
    inProgress: string | null;
    inReview: string | null;
    done: string | null;
  };
  labels: {
    types: string[];
    executors: string[];
    statuses: string[];
    meta: string[];
  };
  branchConvention: string;
  areas: string[];
}

export interface RepoEntry {
  owner: string;
  repo: string;
  name?: string;
}

export interface PackageEntry {
  name: string;
  path: string;
}

export interface Features {
  agents: boolean;
  skills: boolean;
  rules: boolean;
  prompts: boolean;
  commands: boolean;
  mcp: boolean;
  githubAgents: boolean;
  hooks: boolean;
}

export interface McpConfig {
  servers: string[];
}

export interface HooksConfig {
  enabled: boolean;
}

export interface CanonicalFile {
  id: string;
  type: "rule" | "agent" | "skill" | "command" | "prompt" | "github-agent" | "hook";
  description: string;
  scope?: string;
  model?: string;
  protected?: boolean;
  /** Agent runs with restricted write permissions (Cursor v2.5+ subagents). */
  readonly?: boolean;
  /** Agent runs in background without blocking the parent (Cursor v2.5+ async subagents). */
  background?: boolean;
  tags?: string[];
  content: string;
  rawContent: string;
  sourcePath: string;
}

export interface CanonicalMetadata {
  id: string;
  type: string;
  description: string;
  name?: string;
  scope?: string;
  model?: string;
  agent?: string;
  event?: string;
  globs?: string;
  protected?: boolean;
  alwaysApply?: boolean;
  /** Agent runs with restricted write permissions (Cursor v2.5+ subagents). */
  readonly?: boolean;
  /** Agent runs in background without blocking the parent (Cursor v2.5+ async subagents). */
  background?: boolean;
  tags?: string[];
}

export interface ContentSelection {
  preset: "minimal" | "standard" | "full" | "custom";
  projectType: "greenfield" | "brownfield";
  teamSize: "solo" | "team";
  /** Explicit list of selected content IDs (without hatch3r- prefix).
   *  Populated for all presets — the resolved result of preset + context filters. */
  items: {
    agents: string[];
    skills: string[];
    rules: string[];
    commands: string[];
    prompts: string[];
    hooks: string[];
    githubAgents: string[];
  };
}

export interface AdapterOutput {
  path: string;
  content: string;
  /** Inner content for the managed block (used for merge on update). */
  managedContent?: string;
  action: "create" | "update" | "skip";
}

export interface MergeResult {
  path: string;
  action: "created" | "updated" | "skipped";
  warning?: string;
}

export type Framework =
  | "next"
  | "angular"
  | "vue"
  | "svelte"
  | "sveltekit"
  | "remix"
  | "astro"
  | "nuxt"
  | "react"
  | "express"
  | "fastify"
  | "hono"
  | "nestjs"
  | "django"
  | "flask"
  | "rails"
  | "spring"
  | "laravel";

export interface RepoInfo {
  languages: string[];
  packageManager: "npm" | "yarn" | "pnpm" | "bun" | "unknown";
  frameworks: Framework[];
  isMonorepo: boolean;
  hasExistingAgents: boolean;
  existingTools: Tool[];
  rootDir: string;
  /** D14 Medium (#14.5): Detected linter/formatter tools. */
  linters?: string[];
  /** D14 Medium (#14.6): Detected test framework(s). */
  testFrameworks?: string[];
  /** D14 Medium (#14.7): Detected CI provider(s). */
  ciProviders?: string[];
}

export const MANAGED_BLOCK_START = "<!-- HATCH3R:BEGIN -->";
export const MANAGED_BLOCK_END = "<!-- HATCH3R:END -->";
export const HATCH3R_PREFIX = "hatch3r-";
export const AGENTS_DIR = ".agents";
export const ARCHIVE_DIR = ".hatch3r-archive";
export const CUSTOMIZE_DIR = ".hatch3r";

/** Structured error codes for programmatic error handling (e.g., CI scripts). */
export type HatchErrorCode =
  | "VALIDATION_ERROR"
  | "CONFIG_ERROR"
  | "FS_ERROR"
  | "INTEGRITY_ERROR"
  | "ADAPTER_ERROR"
  | "NETWORK_ERROR"
  | "CLEAN_ERROR"
  | "LOCK_TIMEOUT"
  | "UNKNOWN_ERROR";

export class HatchError extends Error {
  constructor(
    message: string,
    public readonly exitCode: number = 1,
    public readonly errorCode: HatchErrorCode = "UNKNOWN_ERROR",
  ) {
    super(message);
    this.name = "HatchError";
  }
}

/** Remove characters that are not alphanumeric, dot, hyphen, or underscore from an ID. */
export function sanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9._-]/g, "");
}

/** Returns id with exactly one hatch3r- prefix (strips existing prefix before adding). */
export function toPrefixedId(id: string, prefix = HATCH3R_PREFIX): string {
  const base = id.replace(new RegExp(`^${prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`), "");
  return `${prefix}${base}`;
}
export const MANIFEST_FILE = "hatch.json";
export const WORKTREE_INCLUDE_FILE = ".worktreeinclude";

export const DEFAULT_FEATURES: Features = {
  agents: true,
  skills: true,
  rules: true,
  prompts: true,
  commands: true,
  mcp: true,
  githubAgents: true,
  hooks: true,
};

export interface McpServerMeta {
  description: string;
  requiresEnv?: string[];
}

export const ENV_VAR_HELP: Record<string, { comment: string; url: string }> = {
  GITHUB_PAT: {
    comment: "GitHub MCP server — Classic PAT: repo, read:org, project. Fine-grained: Contents(RW), Issues(RW), Pull Requests(RW), Projects(RW)",
    url: "https://github.com/settings/tokens/new",
  },
  AZURE_DEVOPS_PAT: {
    comment: "Azure DevOps Personal Access Token (Work Items, Code, Build RW)",
    url: "https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate",
  },
  AZURE_DEVOPS_ORG: {
    comment: "Azure DevOps organization name",
    url: "https://dev.azure.com/",
  },
  GITLAB_TOKEN: {
    comment: "GitLab Personal Access Token (api scope)",
    url: "https://gitlab.com/-/user_settings/personal_access_tokens",
  },
  BRAVE_API_KEY: {
    comment: "Brave Search (free: 2,000 queries/month)",
    url: "https://brave.com/search/api/",
  },
  SENTRY_AUTH_TOKEN: {
    comment: "Sentry error tracking",
    url: "https://sentry.io/settings/account/api/auth-tokens/",
  },
  POSTGRES_URL: {
    comment: "PostgreSQL connection string (e.g. postgresql://user:pass@host:5432/db)",
    url: "",
  },
  LINEAR_API_KEY: {
    comment: "Linear issue tracking",
    url: "https://linear.app/settings/api",
  },
};

export const AVAILABLE_MCP_SERVERS: Record<string, McpServerMeta> = {
  github: {
    description:
      "GitHub repository management, code review, issues, PRs, and project boards",
    requiresEnv: ["GITHUB_PAT"],
  },
  "azure-devops": {
    description:
      "Azure DevOps work items, repos, pipelines, and boards",
    requiresEnv: ["AZURE_DEVOPS_PAT", "AZURE_DEVOPS_ORG"],
  },
  gitlab: {
    description:
      "GitLab issues, merge requests, pipelines, and project management",
    requiresEnv: ["GITLAB_TOKEN"],
  },
  context7: {
    description:
      "Up-to-date, version-specific library documentation for LLMs",
  },
  filesystem: {
    description: "File management and code editing operations",
  },
  playwright: {
    description: "Browser automation, web testing, and UI interaction",
  },
  "brave-search": {
    description:
      "Web research, fact-checking, and current information retrieval",
    requiresEnv: ["BRAVE_API_KEY"],
  },
  sentry: {
    description:
      "Error tracking and performance monitoring (enable and configure with your Sentry auth token)",
    requiresEnv: ["SENTRY_AUTH_TOKEN"],
  },
  postgres: {
    description:
      "PostgreSQL database queries and schema inspection (enable and configure with your connection string)",
    requiresEnv: ["POSTGRES_URL"],
  },
  linear: {
    description:
      "Linear issue tracking and project management (enable and configure with your Linear API key)",
    requiresEnv: ["LINEAR_API_KEY"],
  },
};
